from ubuntu:22.04

RUN apt update
RUN apt install --fix-missing -y \
    sudo python3 python3-pip git

# Add a default user
RUN adduser --disabled-password --gecos "" celestia
RUN echo "celestia ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/celestia

# Copy in bonsoir
COPY ./ /home/celestia/bonsoir
RUN chown -R celestia /home/celestia/bonsoir

# Install bonsoir
USER celestia
RUN pip install --upgrade /home/celestia/bonsoir

# Entrypoint
WORKDIR /home/celestia
ENTRYPOINT bash

